name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        curl -o allure-2.24.0.tgz -OL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.tgz
        sudo tar -zxvf allure-2.24.0.tgz -C /opt/
        sudo ln -s /opt/allure-2.24.0/bin/allure /usr/bin/allure
    
    - name: Check if secrets are set
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: |
        if [ -n "$TEST_EMAIL" ]; then echo "TEST_EMAIL is set: [true]"; else echo "TEST_EMAIL is set: [false]"; fi
        if [ -n "$TEST_PASSWORD" ]; then echo "TEST_PASSWORD is set: [true]"; else echo "TEST_PASSWORD is set: [false]"; fi
        if [ -n "$BINGO_MASK_SALT" ]; then echo "BINGO_MASK_SALT is set: [true]"; else echo "BINGO_MASK_SALT is set: [false]"; fi
      env:
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        BINGO_MASK_SALT: ${{ secrets.BINGO_MASK_SALT }}
    
    - name: Run Cucumber tests
      run: npm run test
      env:
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        BINGO_MASK_SALT: ${{ secrets.BINGO_MASK_SALT }}
    
    - name: Generate Allure Report
      if: always()
      run: allure generate ./allure-results --clean
    
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-${{ matrix.shardIndex }}
        path: allure-report/
        retention-days: 30
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.shardIndex }}
        path: playwright-report/
        retention-days: 30